version: "3.9"
services:
  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8.0.13-fpm-alpine3.15
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: shop-directory
      POSTGRES_DB: shop-directory