version: "3.9"
services:
  nginx:
    container_name: nimiq-shop-directory-backend-nginx
    image: nginx:1.21.4-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - php
  php:
    container_name: nimiq-shop-directory-backend-php
    build:
      context: ./docker/php
    ports:
      - 9005:9000
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
  postgres:
    container_name: nimiq-shop-directory-backend-postgres
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5433:5432
    volumes:
      - ./docker/postgres/persistence:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: shop-directory
      POSTGRES_DB: shop-directory
      POSTGRES_PASSWORD: password
      # TODO: remove this eventually
      POSTGRES_HOST_AUTH_METHOD: trust