version: "3.9"
services:
  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    ports:
      - 9005:9000
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - ./docker/postgres/persistence:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: shop-directory
      POSTGRES_DB: shop-directory
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust